### ISSUE TITLE
Research and understand Nodejs

### ISSUE THREAD

**Issue by plnatoic** [nhat2520/vocabulary_list#5]
## Node.js Fundamentals
Understand how Node.js works, how to create a server, and handle HTTP requests.
## Nest.js Framework
Nest.js is a progressive Node.js framework for building efficient, reliable, and scalable server-side applications. Learn how to use Nest.js to manage routing, middleware, and build web applications.
## Template Engines
Create dynamic web pages, learn a template engine like EJS, Handlebars, or Pug to create and display dynamic content.

**Comment by DUNGTK2004** [comment]
# Update research
## Platfrom: Nodejs
## Framework : ExpressJs(Javascript)
## Combine with Nhat's frontend instead of using template engine
## Support extention to test API: Postman
## Software platform: Docker - helps build, share, and run container applications easier
